name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      - name: docker:dind
        alias: docker

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Maven Build
        run: |
          docker run --rm -v $(pwd):/app -w /app maven:3-jdk-17 mvn package -B

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target/*.jar

  package:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u dahhouilyas --password-stdin

      - name: Docker Build and Push
        run: |
          docker build . -t dahhouilyas/product-microservice
          docker push dahhouilyas/product-microservice

  deploy:
    runs-on: ubuntu-latest

    needs: package

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Docker
        run: docker run -d -p 9001:9001 --name product-microservice dahhouilyas/product-microservice
