name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --dockerd-entrypoint=false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn package -B
      working-directory: maven-build  # Specify the working directory if needed

    - name: Build and push Docker image
      env:
        DOCKER_HUB_USERNAME: dahhouilyas
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        docker build . -t dahhouilyas/product-microservice
        docker login -u dahhouilyas -p $DOCKER_HUB_PASSWORD
        docker push dahhouilyas/product-microservice

    - name: Deploy Docker container
      run: docker run -d -p 9001:9001 --name product-microservice dahhouilyas/product-microservice
